
CDSUNIT_SET_SOURCES := \
	tests/unit/set2/set_insdel_func.cpp \
	tests/unit/set2/set_insdel_func_cuckoo.cpp \
	tests/unit/set2/set_insdel_func_ellentree.cpp \
	tests/unit/set2/set_insdel_func_refinable.cpp \
	tests/unit/set2/set_insdel_func_skip.cpp \
	tests/unit/set2/set_insdel_func_split.cpp \
	tests/unit/set2/set_insdel_func_striped.cpp \
	tests/unit/set2/set_insdel_string.cpp \
    tests/unit/set2/set_insdel_string_michael.cpp \
	tests/unit/set2/set_insdel_string_cuckoo.cpp \
	tests/unit/set2/set_insdel_string_ellentree.cpp \
	tests/unit/set2/set_insdel_string_refinable.cpp \
	tests/unit/set2/set_insdel_string_skip.cpp \
	tests/unit/set2/set_insdel_string_split.cpp \
	tests/unit/set2/set_insdel_string_striped.cpp \
    tests/unit/set2/set_insdel_string_std.cpp \
	tests/unit/set2/set_insdelfind.cpp \
    tests/unit/set2/set_insdelfind_michael.cpp \
	tests/unit/set2/set_insdelfind_cuckoo.cpp \
	tests/unit/set2/set_insdelfind_ellentree.cpp \
	tests/unit/set2/set_insdelfind_refinable.cpp \
	tests/unit/set2/set_insdelfind_skip.cpp \
	tests/unit/set2/set_insdelfind_split.cpp \
	tests/unit/set2/set_insdelfind_striped.cpp \
    tests/unit/set2/set_insdelfind_std.cpp \
	tests/unit/set2/set_delodd.cpp \
	tests/unit/set2/set_delodd_cuckoo.cpp \
	tests/unit/set2/set_delodd_michael.cpp \
	tests/unit/set2/set_delodd_ellentree.cpp \
	tests/unit/set2/set_delodd_skip.cpp \
	tests/unit/set2/set_delodd_split.cpp \
