//$$CDS-header$$

#ifndef CDSLIB_COMPILER_GCC_COMPILER_BARRIERS_H
#define CDSLIB_COMPILER_GCC_COMPILER_BARRIERS_H

#define CDS_COMPILER_RW_BARRIER  __asm__ __volatile__ ( "" ::: "memory" )
#define CDS_COMPILER_R_BARRIER   CDS_COMPILER_RW_BARRIER
#define CDS_COMPILER_W_BARRIER   CDS_COMPILER_RW_BARRIER

#endif  // #ifndef CDSLIB_COMPILER_GCC_COMPILER_BARRIERS_H
